SELECT * FROM CONGTRINH;
SELECT * FROM DIADIEM_CONGTRINH;
SELECT * FROM PHONGBAN;
SELECT * FROM NHANVIEN;
SELECT * FROM SOLUONGNGAYCONG;


--3.1
SELECT MAPB,TENPB
FROM [dbo].[PHONGBAN]
WHERE MAPB = 'PB001'  MAPB = 'PB002'
--3.2
SELECT MANV,HOTEN,NGAYSINH,DIACHI
FROM [dbo].[NHANVIEN]
WHERE DIACHI = N'Đà Nẵng'

--3.3
SELECT PB.MAPB, PB.TENPB, NV.HOTEN AS TENNHANVIEN
FROM [dbo].[PHONGBAN] AS PB, [dbo].[NHANVIEN] AS NV
WHERE PB.MAPB = NV.MAPB AND PB.MAPB = 'PB001';

--3.4
SELECT MANV, HOTEN, NGAYSINH, DIACHI, MAPB
FROM NHANVIEN
WHERE NGAYSINH < '1982-01-01';

--UPDATE NHANVIEN
--SET PHAI = CASE
---    WHEN MANV IN ('NV001', 'NV003','NV004','NV006','NV008','NV010','NV011','NV015') THEN 1
--    WHEN MANV IN ('NV002', 'NV005','NV007','NV009','NV013','NV012','NV014') THEN 0
--    ELSE PHAI
--END;
--3.5
SELECT *
FROM [dbo].[NHANVIEN]
WHERE PHAI = 0 AND DIACHI = N'Quảng Nam';

--3.6
SELECT NV.MANV,NV.HOTEN, SLNC.SOLUONG AS SONGAYCONG
FROM [dbo].[SOLUONGNGAYCONG] AS SLNC,[dbo].[NHANVIEN] AS NV
WHERE SLNC.MANV = NV.MANV 
AND SLNC.MACT = 'CT001';

SELECT NV.MANV, NV.HOTEN, SLNC.SOLUONG AS SONGAYCONG
FROM [dbo].[SOLUONGNGAYCONG] AS SLNC
INNER JOIN [dbo].[NHANVIEN] AS NV
    ON SLNC.MANV = NV.MANV
WHERE SLNC.MACT = 'CT001';

--3.7
SELECT CT.MACT,CT.TENCT,CT.NGAYHT,SLNC.SOLUONG AS SOLUONGNGAYCONG
FROM [dbo].[CONGTRINH] AS CT,[dbo].[SOLUONGNGAYCONG] AS SLNC
WHERE CT.MACT = SLNC.MACT AND CT.NGAYHT <= GETDATE()

SELECT CT.MACT, CT.TENCT, CT.NGAYHT, SLNC.SOLUONG AS SOLUONGNGAYCONG
FROM [dbo].[CONGTRINH] AS CT
INNER JOIN [dbo].[SOLUONGNGAYCONG] AS SLNC
    ON CT.MACT = SLNC.MACT
WHERE CT.NGAYHT <= GETDATE();

--3.8
SELECT NV.MANV, NV.HOTEN, SLNC.MACT, DATEDIFF(YEAR, NV.NGAYSINH, GETDATE()) AS TUOI
FROM [dbo].[NHANVIEN] AS NV
INNER JOIN [dbo].[SOLUONGNGAYCONG] AS SLNC
    ON NV.MANV = SLNC.MANV
INNER JOIN [dbo].[CONGTRINH] AS CT
    ON SLNC.MACT = CT.MACT
WHERE NV.PHAI = 0  -- Nữ
    AND DATEDIFF(YEAR, NV.NGAYSINH, GETDATE()) <= 18;

--, 'NV003','NV004','NV006','NV008','NV010','NV011','NV015'
--, 'NV005','NV007','NV009','NV013','NV012','NV014'

--3.10

SELECT TOP 1 NV.LUONG
FROM [dbo].[NHANVIEN] AS NV
INNER JOIN [dbo].[PHONGBAN] AS PB
   ON PB.MAPB = NV.MAPB
WHERE PB.TENPB = N'Tổng hợp'
ORDER BY NV.LUONG DESC

